services:
  db:
    image: mysql:${TAG}
    env_file:
      - mysql.env
    volumes:
      - C:\Sandesh\Study\New_Project\Vol:/var/lib/mysql
    networks:
      - new_network
    
  web:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    networks:
      - new_network

networks:
  new_network:
    driver: bridge